cmake_minimum_required(VERSION 3.20)
project("Competitive Programming")

# Codeforces uses C++17 or C++20, so we set that here
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# This line tells CLion to analyze and build your specific file

add_executable(B_THU_Packing_Puzzle "Codeforces - Codeforces Round 1092 Unrated Div 2 Based on THUPC 2026  Finals/B_THU_Packing_Puzzle.cpp")
add_executable(C1_Equal_Multisets_Easy_Version "Codeforces - Nebius Round 2 Codeforces Round 1088 Div 1  Div 2/C1_Equal_Multisets_Easy_Version.cpp")
add_executable(C_Stamina_and_Tasks "Codeforces - Codeforces Round 1086 Div 2/C_Stamina_and_Tasks.cpp")
add_executable(D_Divisible_Pairs "1300 rating problems/D_Divisible_Pairs.cpp" "Codeforces - Codeforces Round 925 Div 3/D_Divisible_Pairs.cpp")
add_executable(D_Find_the_Different_Ones "1300 rating problems/D_Find_the_Different_Ones.cpp")
add_executable(E_Romantic_Glasses "1300 rating problems/E_Romantic_Glasses.cpp")
add_executable(D_Divide_and_Equalize "1300 rating problems/D_Divide_and_Equalize.cpp")
add_executable(C_Make_it_Alternating "1300 rating problems/C_Make_it_Alternating.cpp")
add_executable(D_Strong_Vertices "1300 rating problems/D_Strong_Vertices.cpp")
add_executable(Counting_Rooms "Graph Algorithms/Counting_Rooms.cpp")
add_executable(E1_Rudolf_and_Snowflakes_simple_version "1300 rating problems/E1_Rudolf_and_Snowflakes_simple_version.cpp")
add_executable(C_Scoring_Subsequences "1300 rating problems/C_Scoring_Subsequences.cpp")
add_executable(Message_Route "Graph Algorithms/Message_Route.cpp")
add_executable(B_Gardener_and_the_Array "1300 rating problems/B_Gardener_and_the_Array.cpp")
add_executable(F_Yet_Another_Problem_About_Pairs_Satisfying_an_Inequality "1300 rating problems/F_Yet_Another_Problem_About_Pairs_Satisfying_an_Inequality.cpp")
add_executable(G_White_Black_Balanced_Subtrees "1300 rating problems/G_White_Black_Balanced_Subtrees.cpp")
add_executable(H_Maximal_AND "1300 rating problems/H_Maximal_AND.cpp")
add_executable(A_Euclid_Sequence_and_Two_Numbers "Codeforces - Codeforces Round 1102 Div 2/A_Euclid_Sequence_and_Two_Numbers.cpp")
add_executable(B_Palindrome_Twelve_and_Two_Terms "Codeforces - Codeforces Round 1102 Div 2/B_Palindrome_Twelve_and_Two_Terms.cpp")
add_executable(C_Vessels_Heights_and_Two_Versions_Easy_Version "Codeforces - Codeforces Round 1102 Div 2/C_Vessels_Heights_and_Two_Versions_Easy_Version.cpp")
add_executable(D_XOR_Expression_and_Two_Binary_Numbers "Codeforces - Codeforces Round 1102 Div 2/D_XOR_Expression_and_Two_Binary_Numbers.cpp")
add_executable(E_Vlad_Misha_and_Two_Arrays "Codeforces - Codeforces Round 1102 Div 2/E_Vlad_Misha_and_Two_Arrays.cpp")
add_executable(F_Vessels_Heights_and_Two_Versions_Hard_Version "Codeforces - Codeforces Round 1102 Div 2/F_Vessels_Heights_and_Two_Versions_Hard_Version.cpp")
add_executable(G_Stripe_Token_and_Two_Players "Codeforces - Codeforces Round 1102 Div 2/G_Stripe_Token_and_Two_Players.cpp")
add_executable(C_Chat_Ban "1300 rating problems/C_Chat_Ban.cpp")
add_executable(A_AI_Project_Development "Codeforces - Educational Codeforces Round 191 Rated for Div 2/A_AI_Project_Development.cpp")
add_executable(B_Different_Distances "Codeforces - Educational Codeforces Round 191 Rated for Div 2/B_Different_Distances.cpp")
add_executable(C_Cost_of_a_Bracket_Sequence "Codeforces - Educational Codeforces Round 191 Rated for Div 2/C_Cost_of_a_Bracket_Sequence.cpp")
add_executable(D_Goods_on_the_Shelf "Codeforces - Educational Codeforces Round 191 Rated for Div 2/D_Goods_on_the_Shelf.cpp")
add_executable(E1_Permutation_Transmission_Easy_Version "Codeforces - Educational Codeforces Round 191 Rated for Div 2/E1_Permutation_Transmission_Easy_Version.cpp")
add_executable(E2_Permutation_Transmission_Difficult_Version "Codeforces - Educational Codeforces Round 191 Rated for Div 2/E2_Permutation_Transmission_Difficult_Version.cpp")
add_executable(F_Shortest_GCD_Paths "Codeforces - Educational Codeforces Round 191 Rated for Div 2/F_Shortest_GCD_Paths.cpp")
add_executable(A_Array_Elimination "1300 rating problems/A_Array_Elimination.cpp")
add_executable(Problem_2_Mad_Scientist "USACO - USACO 2020 February Contest Bronze/Problem_2_Mad_Scientist.cpp")
add_executable(Problem_3_Watching_Mooloo "USACO - USACO 2023 February Contest Bronze/Problem_3_Watching_Mooloo.cpp")
add_executable(C_Deep_Down_Below "1300 rating problems/C_Deep_Down_Below.cpp")
add_executable(B_Box_Fitting "1300 rating problems/B_Box_Fitting.cpp")
add_executable(A_Games_on_the_Train "Codeforces - Codeforces Round 1103 Div 3/A_Games_on_the_Train.cpp")
add_executable(B_Tatar_TV_Show "Codeforces - Codeforces Round 1103 Div 3/B_Tatar_TV_Show.cpp")
add_executable(C_Omsk_Programmers "Codeforces - Codeforces Round 1103 Div 3/C_Omsk_Programmers.cpp")
add_executable(D_Brand_New_Tatar_TV_Show "Codeforces - Codeforces Round 1103 Div 3/D_Brand_New_Tatar_TV_Show.cpp")
add_executable(E_Friendly_Gifts "Codeforces - Codeforces Round 1103 Div 3/E_Friendly_Gifts.cpp")
add_executable(F1_Elections_in_Saransk_easy_version "Codeforces - Codeforces Round 1103 Div 3/F1_Elections_in_Saransk_easy_version.cpp")
add_executable(F2_Elections_in_Saransk_hard_version "Codeforces - Codeforces Round 1103 Div 3/F2_Elections_in_Saransk_hard_version.cpp")
add_executable(G_Criterion_in_Burlandia "Codeforces - Codeforces Round 1103 Div 3/G_Criterion_in_Burlandia.cpp")
add_executable(A_Strange_Birthday_Party "1300 rating problems/A_Strange_Birthday_Party.cpp")
add_executable(C1_Seating_Arrangement_Easy_Version "Random Question 1200 - 1400/C1_Seating_Arrangement_Easy_Version.cpp")
add_executable(B_Move_and_Turn "1300 rating problems/B_Move_and_Turn.cpp")
add_executable(A_Magic_of_Squares "Codeforces - Contest 8/A_Magic_of_Squares.cpp")
add_executable(A_Destroying_Towers "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/A_Destroying_Towers.cpp")
add_executable(B_Annoying_the_Ghost "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/B_Annoying_the_Ghost.cpp")
add_executable(C_Duck_Surplus "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/C_Duck_Surplus.cpp")
add_executable(D_Fullmetal_Bitchemist "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/D_Fullmetal_Bitchemist.cpp")
add_executable(E_Permutation_Commutation "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/E_Permutation_Commutation.cpp")
add_executable(F_Paint_the_Array "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/F_Paint_the_Array.cpp")
add_executable(G_Send_GCDs "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/G_Send_GCDs.cpp")
add_executable(H_Slime_and_Queries "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/H_Slime_and_Queries.cpp")
add_executable(I1_DBFS_Order_Easy_Version "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/I1_DBFS_Order_Easy_Version.cpp")
add_executable(I2_DBFS_Order_Hard_Version "Codeforces - Order Capital Round 2 Codeforces Round 1104 Div 1  Div 2/I2_DBFS_Order_Hard_Version.cpp")
add_executable(1400A_Basketball_Exercise "Codeforces - Dynamic Programming Easy/1400A_Basketball_Exercise.cpp")
add_executable(1400B_Constanzes_Machine "Codeforces - Dynamic Programming Easy/1400B_Constanzes_Machine.cpp")
add_executable(A_Secret_Passwords "Codeforces - Graphs/A_Secret_Passwords.cpp")
add_executable(B_Omkar_and_Last_Class_of_Math "1300 rating problems /B_Omkar_and_Last_Class_of_Math.cpp")
add_executable(B_Lunar_New_Year_and_a_Wander "Codeforces - Graphs/B_Lunar_New_Year_and_a_Wander.cpp")
add_executable(1500A_Woodcutters "Codeforces - Dynamic Programming Easy/1500A_Woodcutters.cpp")
add_executable(Dice_Combinations "CSES - CSES Problem Set/Dice_Combinations.cpp")
add_executable(A_Minimize_Arrangement "Codeforces - TSA-2026 Contest-9/A_Minimize_Arrangement.cpp")
add_executable(B_Value_of_an_Expression "Codeforces - TSA-2026 Contest-9/B_Value_of_an_Expression.cpp")
add_executable(C_Journey "Codeforces - Graphs/C_Journey.cpp")
add_executable(1500B_Pie_Rules "Codeforces - Dynamic Programming Easy/1500B_Pie_Rules.cpp")
add_executable(Minimizing_Coins "CSES - CSES Problem Set/Minimizing_Coins.cpp")
add_executable(B_Shuffle "1300 rating problems /B_Shuffle.cpp")
add_executable(Coin_Combinations_I "CSES - CSES Problem Set/Coin_Combinations_I.cpp")
add_executable(1500C_Polycarp_and_Div_3 "Codeforces - Dynamic Programming Easy/1500C_Polycarp_and_Div_3.cpp")
add_executable(A_Another_Popcount_Problem "Codeforces - Codeforces Round 1105 Div 2/A_Another_Popcount_Problem.cpp")
add_executable(B_AI_Finds_Nothing_Here "Codeforces - Codeforces Round 1105 Div 2/B_AI_Finds_Nothing_Here.cpp")
add_executable(C_Nim_Game_Is_XOR_Game "Codeforces - Codeforces Round 1105 Div 2/C_Nim_Game_Is_XOR_Game.cpp")
add_executable(D_Decidophobia "Codeforces - Codeforces Round 1105 Div 2/D_Decidophobia.cpp")
add_executable(E_Revival "Codeforces - Codeforces Round 1105 Div 2/E_Revival.cpp")
add_executable(B_Most_socially_distanced_subsequence "Codeforces - Codeforces Round 649 Div 2/B_Most_socially_distanced_subsequence.cpp")
add_executable(D_Buying_Shovels "1300 rating problems /D_Buying_Shovels.cpp" "Codeforces - Codeforces Round 644 Div 3/D_Buying_Shovels.cpp")
add_executable(D_Cyclic_Components "Codeforces - Graphs/D_Cyclic_Components.cpp")
add_executable(Coin_Combinations_II "CSES - CSES Problem Set/Coin_Combinations_II.cpp")